networks:
  webnet:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: "192.168.100.0/24"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "0.0.0.0:8080:80"
    volumes:
      - ./src:/var/www/html
      - ./audio_files:/var/www/audio_files
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - webnet
    dns:
      - 1.1.1.1
      - 1.0.0.1

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./audio_files:/var/www/audio_files
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - webnet
    dns:
      - 1.1.1.1
      - 1.0.0.1